name: Deploy to GitHub Pages (Simple)

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name if different
  workflow_dispatch:    # Allow manual triggering

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Create docs directory
      run: mkdir -p docs
      
    - name: Create placeholder page
      run: |
        BACKEND_URL="${{ secrets.BACKEND_URL || secrets.DOMAIN_NAME || secrets.SSH_HOST }}"
        
        # Create a simple placeholder page
        cat > docs/index.html << EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poker Tower Defense</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            color: #333;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            text-align: center;
        }
        .container {
            max-width: 800px;
            padding: 20px;
            background-color: white;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #2c3e50;
        }
        .button {
            display: inline-block;
            background-color: #3498db;
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            text-decoration: none;
            margin-top: 20px;
            transition: background-color 0.3s;
        }
        .button:hover {
            background-color: #2980b9;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Poker Tower Defense</h1>
        <p>The game client is being set up. Please check back later.</p>
        <p>Backend URL: <strong>${BACKEND_URL}</strong></p>
        <a href="https://${BACKEND_URL}" class="button">Check Backend Status</a>
    </div>
</body>
</html>
EOF
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages 